# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('EventDate', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=100)),
                ('EventType', models.CharField(choices=[('bridal', 'Bridal'), ('bridal shower', 'Bridal Shower'), ('engagement', 'Engagement'), ('baby shower', 'Baby Shower'), ('birthday', 'Birthday'), ('school event', 'School Event'), ('friends/family reunion', 'Friends/Family ReUnion'), ('others', 'Others')], default='bridal', max_length=50)),
                ('Message', models.CharField(max_length=200)),
            ],
        ),
    ]
